### ISSUE TITLE
Issue to start a new environnment

### ISSUE THREAD

**Issue by Nicolas99-9** [AdrianP-/gym_trading#3]
I try to create a new environnment but I have a problem : 

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    env = gym.make('trading-v0')
  File "/home/nicolas/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 163, in make
    return registry.make(id)
  File "/home/nicolas/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 121, in make
    patch_deprecated_methods(env)
  File "/home/nicolas/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 181, in patch_deprecated_methods
    env.seed  = env._seed
AttributeError: 'TradingEnv' object has no attribute '_seed'

Versions : 
gym (0.9.6)

Does it requires an older version of gym ?

**Comment by Nicolas99-9** [comment]
Edit : 
I fixed it by adding self._seed = 99 in "trading_env.py".

**Comment by AdrianP-** [comment]
Thanks @Nicolas99-9

**Comment by jalalmzh** [comment]
@AdrianP
Hi guys
How can I fix this error?

-------------------------------------------------------------------------------------
runfile('C:/Users/jalal/Desktop/RL/gym_trading-master/run.py', wdir='C:/Users/jalal/Desktop/RL/gym_trading-master')
Traceback (most recent call last):

  File "<ipython-input-18-95afd8abf54f>", line 1, in <module>
    runfile('C:/Users/jalal/Desktop/RL/gym_trading-master/run.py', wdir='C:/Users/jalal/Desktop/RL/gym_trading-master')

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/jalal/Desktop/RL/gym_trading-master/run.py", line 2, in <module>
    import gym_trading

  File "C:\Users\jalal\Desktop\RL\gym_trading-master\gym_trading\__init__.py", line 5, in <module>
    entry_point='gym_trading.envs:TradingEnv'

  File "C:\Anaconda3\lib\site-packages\gym\envs\registration.py", line 164, in register
    return registry.register(id, **kwargs)

  File "C:\Anaconda3\lib\site-packages\gym\envs\registration.py", line 157, in register
    raise error.Error('Cannot re-register id: {}'.format(id))

Error: Cannot re-register id: trading-v0
